apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: authelia

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: authelia

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: authelia
    repoURL: https://charts.authelia.com
    targetRevision: ~0.8.1
    helm:
      releaseName: authelia
      values: |
        domain: chenchik.me
        ingress:
          enabled: true
          subdomain: auth
          traefikCRD:
            enabled: true
            entryPoints:
              - websecure
            tls:
              options:
                minVersion: VersionTLS12
                maxVersion: VersionTLS13
                curvePreferences:
                - CurveP521
                - CurveP384
                cipherSuites:
                - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
                - TLS_RSA_WITH_AES_256_GCM_SHA384
                sniStrict: true
              certResolver: acme-http
        configMap:
          authentication_backend:
            ldap:
              enabled: false
            file:
              enabled: true
              path: /config/users/users_database.yaml
          access_control:
            rules:
            - domain: "*.chenchik.me"
              policy: one_factor
          session:
            redis:
              enabled: false
          storage:
            local:
              enabled: true
            postgres:
              enabled: false
          notifier:
            filesystem:
              enabled: true
            smtp:
              enabled: false
          server:
            read_buffer_size: 65536
            write_buffer_size: 65536
        pod:
          type: StatefulSet
          extraVolumeMounts:
            - name: users-database
              mountPath: "/config/users"
              readOnly: true
          extraVolumes:
            - name: users-database
              secret:
                secretName: authelia-users
                items:
                  - key: users_database.yaml
                    path: users_database.yaml
