apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-dashboard
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`minio.chenchik.me`)
      services:
        - name: minio-console
          port: 9001
