apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api
  namespace: enableops
spec:
  values:
    vault:
      app:
        injectSecrets:
          toFiles: true
          pathToSecret: "db"
          mountPath: /secrets
          policy: postgres-vaultinject
