apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: local
servers: 1
agents: 1
volumes:
  - volume: /Volumes/Cluster/PVC:/var/lib/rancher/k3s/storage # persist PVC on host
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: "127.0.0.1:80:80"
    nodeFilters:
      - loadbalancer
  - port: "127.0.0.1:5432:5432"
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: k3d-registry
    host: "127.0.0.1"
    hostPort: "5000"
