apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: root

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    repoURL: https://github.com/AndreiChenchik/dev-cluster
    path: apps
    targetRevision: HEAD
