apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.toml: |-
    [server]
    port = 8989
    hostname = "https://podcasts.chenchik.me/file/podcasts-chenchik-me"

    [storage]
      type = "s3"

      [storage.s3]
      endpoint_url = "https://s3.eu-central-003.backblazeb2.com"
      region = "eu-central-003"
      bucket = "podcasts-chenchik-me"

    [tokens]
    youtube = ""

    [feeds]
      [feeds.OTG]
      page_size = 50
      url = "https://www.youtube.com/playlist?list=PLB-qPpAk87uJmBIo8RFyvQIYUNgmghx_a"
      update_period = "1h"
      quality = "high"
      format = "audio"
      playlist_sort = "asc"
      clean = { keep_last = 50 }

      [feeds.OTG.custom]
      title = "YouTube On The Go"
      description = "Audio version of my YouTube playlist"
      cover_art = "https://f003.backblazeb2.com/file/podcasts-chenchik-me/OTG.png"
      cover_art_quality = "high"
      category = "News"
      subcategories = ["News", "Tech News"]
      explicit = true
      lang = "en"
      author = "Andrei Chenchik (andrei@chenchik.me)"
      ownerName = "Andrei Chenchik"
      ownerEmail = "andrei@chenchik.me"

    [downloader]
    self_update = true
    timeout = 180
