apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: authelia-helm
        namespace: flux-system
      version: "~0.8.1"
  interval: 60m0s
  install:
    remediation:
      retries: -1
  values:
    domain: chenchik.me
    ingress:
      enabled: true
      subdomain: auth
      traefikCRD:
        enabled: true
        entryPoints:
          - web
        tls:
          options:
            minVersion: VersionTLS12
            maxVersion: VersionTLS13
            curvePreferences:
              - CurveP521
              - CurveP384
            cipherSuites:
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_RSA_WITH_AES_256_GCM_SHA384
            sniStrict: true
          certResolver: acme-http
    configMap:
      authentication_backend:
        ldap:
          enabled: false
        file:
          enabled: true
          path: /config/users/users_database.yaml
      access_control:
        rules:
          - domain: "*.chenchik.me"
            policy: one_factor
      session:
        redis:
          enabled: false
      storage:
        local:
          enabled: true
        postgres:
          enabled: false
      notifier:
        filesystem:
          enabled: true
        smtp:
          enabled: false
      server:
        read_buffer_size: 65536
        write_buffer_size: 65536
    pod:
      type: StatefulSet
      extraVolumeMounts:
        - name: users-database
          mountPath: "/config/users"
          readOnly: true
      extraVolumes:
        - name: users-database
          secret:
            secretName: authelia-users
            items:
              - key: users_database.yaml
                path: users_database.yaml
