apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute

metadata:
  name: vault-dashboard
  namespace: vault

spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`vault.chenchik.me`)
      services:
        - name: vault
          namespace: vault
          port: 8200
