apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: chenchik-helm
        namespace: flux-system
      version: "~0.0.43"
  interval: 1m0s
  install:
    remediation:
      retries: -1
  values:
    vault:
      server:
        configure:
          init: true
          unseal: true
          enableK8sAuth: true
          enableGithubAuth: true
          enableKVEngine: true
          spawnPolicies: true
          spawnRandomSecrets: true

        githubAuth:
          org: enableops
          teamPolicies: |
            [{  "team": "dev_team",
                "policy": "gh-enableops-dev_team" }]

        k8roles: |
          [{  "role": "postgres-vaultinject",
              "policy": "postgres-vaultinject",
              "serviceAccount": "postgres-vaultinject",
              "namespace": "enableops"
          },
          {   "role": "enableops-api-vaultinject",
              "policy": "enableops-api-vaultinject",
              "serviceAccount": "enableops-api-vaultinject",
              "namespace": "enableops"
          }]

        policies: |
          [{  "name": "gh-enableops-dev_team",
              "policy": { "path": { "secrets/*": {
                "capabilities": [ "create", "read", "update", "delete", "list" ]
              }}}
          },
          {   "name": "postgres-vaultinject",
              "policy": { "path": { "secrets/data/db": {
                "capabilities": [ "read" ]
              }}}
          },
          {   "name": "enableops-api-vaultinject",
              "policy": { "path": { "secrets/data/api": {
                "capabilities": [ "read" ]
              }}}
          }]

        randomSecrets: |
          [{  "path": "secrets/db",
              "keys": [ "POSTGRES_PASSWORD" ]
          }]
