apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik-helm
        namespace: flux-system
      version: "~10"
  interval: 60m0s
  install:
    remediation:
      retries: -1
  values:
    additionalArguments:
      - --accesslog=true
      - --log.level=DEBUG
      - --api=true
      - --api.dashboard=true
    service:
      type: LoadBalancer
