apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
spec:
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio-helm
        namespace: flux-system
      version: "~4.0.2"
  interval: 1m0s
  install:
    remediation:
      retries: -1
