apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: jupyterhub

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: jupyterhub
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: "~1.2.0"
    helm:
      releaseName: jupyterhub
      values: |
        hub:
          config:
            GitHubOAuthenticator:
              client_id: 01017503416e3be48451
              client_secret: 74a15682a25ffe8d4b3e9ec4b7ca23190aa6698e
              oauth_callback_url: https://jupyter.chenchik.me/hub/oauth_callback
              allowed_organizations:
                - enableops
              scope:
                - read:org
            Authenticator:
              admin_users:
                - AndreiChenchik
              auto_login: true
            JupyterHub:
              authenticator_class: github
        singleuser:
          image:
            name: jupyter/tensorflow-notebook
            tag: 2022-02-07
        proxy:
          service:
            type: ClusterIP
