apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: enableops-api

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: enableops-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: web-app
    repoURL: https://helm.chenchik.me/
    targetRevision: "~0.4.0-0"
    helm:
      releaseName: enableops-api
      values: |
        image:
          repository: "eu.gcr.io/enableops-io/api"
          tag: "0.8.2"
          pullSecret: "eu-gcr-io"

        ingressHost: eops-api.chenchik.me

        service:
          targetPort: 8000

        config:
          API_ENV_STATE: dev
          API_SECRETS_PATH: "/secrets"

        vault:
          app:
            injectSecrets:
              toFiles: true

              pathToSecret: "api"
              mountPath: "/secrets"
              policy: enableops-api-inject
