# Remove until https://github.com/prometheus-community/helm-charts/issues/1500 fixed
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   namespace: argocd

#   name: prometheus

#   finalizers:
#     - resources-finalizer.argocd.argoproj.io

#   annotations:
#     argocd.argoproj.io/sync-wave: "1"

# spec:
#   project: default

#   destination:
#     server: https://kubernetes.default.svc
#     namespace: prometheus

#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - Validate=true
#       - CreateNamespace=true
#       - Replace=true

#   source:
#     chart: kube-prometheus-stack
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 30.2.0
#     helm:
#       releaseName: prometheus
#       parameters:
#         - name: prometheus-node-exporter.hostRootFsMount
#           value: "false"
