apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: external-secrets

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true

  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: "0.4.1"
    helm:
      releaseName: external-secrets
