apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: traefik

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: ~10
    helm:
      releaseName: traefik
      values: |
        additionalArguments:
          - --accesslog=true
          - --log.level=DEBUG
          - --api=true
          - --api.dashboard=true
        service:
          type: LoadBalancer
