apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: postgres

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: enableops-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true

  source:
    chart: postgres
    repoURL: https://helm.chenchik.me/
    targetRevision: "*"
    helm:
      releaseName: postgres
      values: |
        vault:
          app:
            injectSecrets:
              toFiles: true

              pathToSecret: "db"
              mountPath: /secrets
              policy: postgres-inject
