apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: vault

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: vault
    repoURL: https://helm.chenchik.me/
    targetRevision: ~0.0.1
    helm:
      releaseName: vault
      values: |
        vault:
          server:
            ha:
              enabled: true
              replicas: 2

          jobs:
            init: true
            unseal: true
            enableK8sAuth: true
