apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: vault

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: vault
    repoURL: https://helm.chenchik.me
    targetRevision: "~0.0.43"
    helm:
      releaseName: vault
      values: |
        vault:
          server:
            configure:
              init: true
              unseal: true
              enableK8sAuth: true
              enableGithubAuth: true
              enableKVEngine: true
              spawnPolicies: true   
              spawnRandomSecrets: true       

            githubAuth:
              org: enableops
              teamPolicies: |
                [{  "team": "dev_team",
                    "policy": "gh-enableops-dev_team" }]

            k8roles: |
              [{  "role": "postgres-vaultinject",
                  "policy": "postgres-vaultinject",
                  "serviceAccount": "postgres-vaultinject",
                  "namespace": "enableops-api"
              }]

            policies: |
              [{  "name": "gh-enableops-dev_team",
                  "policy": { "path": { "secrets/*": {
                    "capabilities": [ "create", "read", "update", "delete", "list" ]
                  }}}
              },
              {   "name": "postgres-vaultinject",
                  "policy": { "path": { "secrets/data/db": {
                    "capabilities": [ "read" ]
                  }}}
              }]

            randomSecrets: |
              [{  "path": "secrets/db",
                  "keys": [ "POSTGRES_PASSWORD" ]
              }]
