apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: vault

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: vault
    repoURL: https://helm.chenchik.me/
    targetRevision: ~0.0.1
    helm:
      releaseName: vault
      values: |
        vault:
          server:
            configure:
              init: true
              unseal: true
              enableK8sAuth: true
              enableGithubAuth: true
              enableKVEngine: true
              configureK8sRole: true
              spawnPolicies: true
              spawnRandomSecrets: true            

            kvEndpoint: secrets
            
            githubAuth:
              org: enableops
              teamPolicies: |
                [{  "team": "dev_team",
                    "policy": "gh-enableops-dev_team" }]

            policies: |
              [{  "name": "gh-enableops-dev_team",
                  "policy": { "path": { "secrets/*": {
                    "capabilities": ["create", "read", "update", "delete", "list"]
                  }}}
              }]

            randomSecrets: |
              [{  "path": "secrets/app-secret",
                  "keys": [ "first",
                            "second",
                            "other" ]
              }]

          app:            
            injectSecrets:
              toEnv: false
              toFiles: false

              pathToSecret: "somefolder/somesecret"
              keysToInject:
                - first
                - second
              
              mountPath: /secrets

              policy: test-policy24
              role: test-role
              serviceAccount: service-account1
