apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd

  name: jupyterhub

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    chart: jupyterhub
    repoURL: https://jupyterhub.github.io/helm-chart/
    targetRevision: "~1.2.0"
    helm:
      releaseName: jupyterhub
      values: |
        singleuser:
          image:
            name: jupyter/datascience-notebook
            tag: 2022-02-07
