apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enableops-api
spec:
  project: default
  source:
    repoURL: https://github.com/AndreiChenchik/dev-cluster
    path: charts/python
    targetRevision: HEAD
    helm:
      parameters:
      - name: name
        value: enableops-api
      - name: targetPort
        value: 8000
      - name: host
        value: api.local
      - name: pullSecret
        value: eu-gcr-io
      - name: image
        value: eu.gcr.io/enableops-io/api:0.6.40
      - name: envSecret
        value: enableops-api-env
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-apps
