apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  
  name: eops-api
  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  project: default
  
  destination:
    server: https://kubernetes.default.svc
    namespace: eops-api
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true

  source:
    repoURL: https://github.com/AndreiChenchik/dev-cluster
    path: charts/python-app
    targetRevision: HEAD
    
    helm:
      parameters:
      - name: name
        value: "eops-api"
      - name: host
        value: "api.local"
      - name: targetPort
        value: "8000"
      - name: image
        value: "eu.gcr.io/enableops-io/api:0.6.40"
      - name: pullSecret
        value: "eu-gcr-io"
      - name: envSecret
        value: "enableops-api-env"
