apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{.Values.name}}

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{.Values.name}}

  template:
    metadata:
      labels:
        app: {{.Values.name}}

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{.Values.name}}
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "kv/data/api/database/config"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: |
          {{"{{"}}- with secret "kv/data/api/database/config" -{{"}}"}}
          {{"{{"}} range $k, $v := .Data.data {{"}}"}}
          {{"{{"}} $k {{"}}"}}: {{"{{"}} $v {{"}}"}}
          {{"{{"}} end {{"}}"}}
          postgresql://{{"{{"}} .Data.data.username {{"}}"}}:{{"{{"}} .Data.data.password {{"}}"}}@postgres:5432/wizard
          {{"{{"}}- end {{"}}"}}

    spec:
      serviceAccountName: {{.Values.name}}

      containers:
        - image: {{.Values.image}}
          name: {{.Values.name}}

          ports:
            - containerPort: {{.Values.targetPort}}

          envFrom:
            - secretRef:
                name: {{.Values.envSecret}}

      imagePullSecrets:
        - name: {{.Values.pullSecret}}
