apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{.Values.name}}

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: {{.Values.name}}

  template:
    metadata:
      labels:
        app: {{.Values.name}}

      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: {{.Values.name}}
        vault.hashicorp.com/agent-inject-secret-spawn: "kv/data/api/database/config"
        vault.hashicorp.com/agent-inject-template-spawn: |
          {{- `
          {{- with secret "kv/data/api/database/config" -}}
          {{- range $k, $v := .Data.data }}
          echo {{ $k }} > /vault/secrets/{{ $v }}
          {{- end }}{{ end }}
          rm /vault/secrets/spawn
          `}}
        vault.hashicorp.com/agent-inject-perms-spawn: "0777"
        vault.hashicorp.com/agent-inject-command-spawn: "/vault/secrets/spawn"

    spec:
      serviceAccountName: {{.Values.name}}

      containers:
        - image: {{.Values.image}}
          name: {{.Values.name}}

          ports:
            - containerPort: {{.Values.targetPort}}

          envFrom:
            - secretRef:
                name: {{.Values.envSecret}}

      imagePullSecrets:
        - name: {{.Values.pullSecret}}
