apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
spec:
  chart:
    spec:
      chart: postgres
      sourceRef:
        kind: HelmRepository
        name: chenchik-helm
        namespace: flux-system
      interval: 1m
  interval: 1m
  install:
    remediation:
      retries: -1
